### ISSUE TITLE
Help needed: service / characteristic ID for button press?

### ISSUE THREAD

**Issue by ragcsalo** [inFullMobile/inFullBand#1]
This is not an issue, I just need some help. I'd like to make a BT LE communication app for the Mi Band 2, which would recognise button presses. The only thing I can't find is the service / characteristic ID for button press. Could you help me with that, please? Many thanks in advance!!! :-)

**Comment by abelduran1** [comment]
The button touch UUID -> public static final UUID UUID_CHARACTERISTIC_DEVICEEVENT = UUID.fromString("00000010-0000-3512-2118-0009af100700");

 extracted from here: https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java

**Some useful links:**

In this project you can find all tou need -> https://github.com/Freeyourgadget/Gadgetbridge

https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandService.java

https://github.com/Freeyourgadget/Gadgetbridge/issues/741

https://github.com/Freeyourgadget/Gadgetbridge/blob/238bacde9f6fd59f3b39f17cc29dee82b6932a96/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java

**Comment by ragcsalo** [comment]
Thanks! :-) I tried to get notified when this characteristic changes, but nothing happened when I touched the button... I use the BT LE Central plugin for Cordova (both iOS and Android). Maybe there's something I'm missing, I don't know. I will keep trying... Thanks for your help! :-)

Cordova plugin: https://github.com/don/cordova-plugin-ble-central

My code to subscribe for the notification:

`ble.startNotification(uid, "FEE0", "00000010-0000-3512-2118-0009AF100700", function() {alert('Button pressed');}, function() {alert('ERROR');});`

(where variable 'uid' contains the ID of the Mi Band 2 - after a successfull connection)

**Comment by ragcsalo** [comment]
When I try to subscribe for notifications for characteristic "00000010-0000-3512-2118-0009AF100700", I get this error:

`Error Domain=CBATTErrorDomain Code=3 "Writing is not permitted"`

I've read in a post that before subscribing for notifications, I have to write some characteristic to indicate I want to communicate with the device... but ' don't understand it at all. :-(

Here is the post I'm referring to: https://stackoverflow.com/questions/29030283/writing-is-not-permitted-error-when-attempting-to-subscribe-to-cbcharacteristic

**Comment by ghost** [comment]
@ragcsalo I've added the functionality of receiving button press notifications to my app, so you can check how it works. However, I don't know the Cordova plugin you mentioned so I can't help you with that. As for writing to some characteristics just to be able to subscribe - I didn't need such thing. It could be a specific behaviour of the device mentioned in the StackOverflow post you've linked.

PS. Sorry for long response time - I didn't get a notification from GitHub about your issue.

**Comment by ragcsalo** [comment]
Thanks! :-) It works now on Android, but on iOS I still get the error message... :/

**Comment by ghost** [comment]
I'm closing the issue as I don't see any more feedback I could provide.
