### ISSUE TITLE
Not working for MI band 3 and HRX

### ISSUE THREAD

**Issue by Haridasan** [inFullMobile/inFullBand#4]
Hi,
 I am using your code to interact with MI bands and it is working fine with MI band 2 but for band 3 it is returning null value even it is having some value. Please explain this issue and thank you very much for your code.

**Comment by mikchmie** [comment]
Hi Haridasan. Every Bluetooth device can have its own unique Bluetooth communication interface, which means that Mi Band 3 probably has the same functionalities, as Mi Band 2, available under different UUIDs. You would have to dig into communication protocol of this model and find UUIDs of characteristics and services which can then be used to acquire data used by this app. You can check [Gadgetbridge project](https://github.com/Freeyourgadget/Gadgetbridge), maybe they've already figured it out. Also I don't have access to Mi Band 3 so I'm not able to experiment with it.
